version: '2.1'

services:
  zipkin:
    image: "openzipkin/zipkin"
    hostname: zipkin
    ports:
      - "9411:9411"
  company-bulletin-board:
    image: "servicecomb/service-center"
    hostname: service-center
    ports:
      - "30100:30100"

  company-worker:
    image: "worker:0.0.1-SNAPSHOT"
    hostname: worker
    links:
      - "company-bulletin-board:sc.servicecomb.io"
      - "zipkin:zipkin.io"
    environment:
      - JAVA_OPTS="-Dcse.service.registry.address=http://sc.servicecomb.io:30100"
      - ARTIFACT_ID=worker
    ports:
      - "7070:7070"
      - "8080:9091"
    healthcheck:
        test: ["CMD-SHELL", "nc -z localhost 7070 &> /dev/null; echo $$?"]
        interval: 30s
        timeout: 10s
        retries: 5

  company-doorman:
    image: "doorman:0.0.1-SNAPSHOT"
    hostname: doorman
    links:
      - "company-bulletin-board:sc.servicecomb.io"
      - "zipkin:zipkin.io"
    environment:
      - JAVA_OPTS="-Dcompany.auth.secret=someSecretKey -Dcse.service.registry.address=http://sc.servicecomb.io:30100"
      - ARTIFACT_ID=doorman
    ports:
      - "8081:9092"

  company-beekeeper:
    image: "beekeeper:0.0.1-SNAPSHOT"
    hostname: beekeeper
    links:
      - "company-bulletin-board:sc.servicecomb.io"
      - "zipkin:zipkin.io"
      - "company-worker"
    environment:
      - JAVA_OPTS="-Dcse.service.registry.address=http://sc.servicecomb.io:30100"
      - ARTIFACT_ID=beekeeper
    depends_on:
      company-worker:
        condition: service_healthy
    ports:
      - "8082:9093"

  company-manager:
    image: "manager:0.0.1-SNAPSHOT"
    hostname: manager
    links:
      - "company-bulletin-board:sc.servicecomb.io"
      - "zipkin:zipkin.io"
    environment:
      - JAVA_OPTS="-Dcse.service.registry.address=http://sc.servicecomb.io:30100"  #-Dlogging.level.root=DEBUG
      - ARTIFACT_ID=manager
    ports:
      - "8083:8080"
